### ISSUE TITLE
compatibility with modded elytras

### ISSUE THREAD

**Issue by milkev** [TheIllusiveC4/CuriousElytra#10]
**Please describe the new feature or change.**
compatibility with modded elytra's such as those from enderite or netherite plus (the only ones i know of) would be awesome! 

**Please describe why you want this feature.**
so that the mod doesnt become unusable if you want the higher durability of modded elytras, or just craft one... and find its not compatible.
it also doesnt make sense from an in-game standpoint that upgrading a tool would make it no longer be able to be put in a slot.

**Comment by SilentChaos512** [comment]
Is it not possible to just support any modded elytra? This still does not fix the issue for Silent Gear. Or is there something I can do to fix this on my end? Related issue here: https://github.com/SilentChaos512/Silent-Gear/issues/302

**Comment by TheIllusiveC4** [comment]
@SilentChaos512 I believe your issue might be caused by your Caelus compatibility [here](https://github.com/SilentChaos512/Silent-Gear/blob/12dffc98057b970cbf371183175b4c96ac0e0bb5/src/main/java/net/silentchaos512/gear/compat/caelus/CaelusCompatProxy.java#L12).

You're using the modifier that Caelus uses for the vanilla elytra item. However, this is only meant to be used for the vanilla elytra implementation by Caelus and shouldn't be implemented by other modders. It's only exposed in the API as a reference in case modders really do need that specific modifier. It only works in the chest slot as it is because it happens to extend `ElytraItem`, but that logic breaks when in any other slot. In your case, I think you just need to replace that with a similar modifier with an alternative UUID and it should solve the issue.

On another note, I think I still need to change the rendering code on my end so that your Elytra item would render properly in the back slot. 

Edit: On the subject of supporting any modded elytra, most modded elytra implementations should work with the current infrastructure of Curious Elytra natively. However, properly rendering the right elytra textures is more complicated and I have to hardcode that integration currently until I figure out a better solution.
