### ISSUE TITLE
[Compat]: Feathers

### ISSUE THREAD

**Issue by MaxWasUnavailable** [TheIllusiveC4/CuriousElytra#127]
### What is the new feature or improvement?

Also reported at Feathers, here: https://github.com/ElenaiDev/Feathers/issues/50

It seems elytra in a slot cause significant log spam with Feathers, since they're not classified as armour. Is there any chance you could provide compatibility from your end for this?

**Comment by TheIllusiveC4** [comment]
I don't think this is an Elytra Slot issue since Feathers seems to be checking the armor slots (not the accessory slots). In addition, even then, that would need to be resolved by Feathers since it seems they will log an error whenever a non-armor item exists in an armor slot (which can happen often in a modded ecosystem).
