### ISSUE TITLE
Wavey Capes compatibility

### ISSUE THREAD

**Issue by Inqie** [TheIllusiveC4/CuriousElytra#32]
When Wavey Capes (Forge) is installed, the cape does not disappear when elytra is equipped in the Curios slot. 

Expected behaviour, of course, is that the cape should disappear when any elytra is equipped in any slot.

To reproduce, just equip an elytra in the Curios slot with the two mods installed.

**System Info:**
Minecraft Version: 1.16.5
Forge Version: 36.2.9
Caelus Version: 2.1.3.1
Curios Version: 4.0.5.3
Curious Elytra Version: 4.0.2.3
Wavey Capes Version: 1.0.4
Java Version: 1.8.0_242 64bit
CPU: 16x AMD Ryzen 9 5900HX with Radeon Graphics
GPU: NVIDIA GeForce RTX 3070 Laptop GPU/PCIe/SSE2

**Comment by TheIllusiveC4** [comment]
I believe this will need something done from WaveyCapes first, since they're the ones implementing the cape. Perhaps something like an API method that exposes whether a cape is active or not, or they can check for the Curious Elytra slot themselves. Regardless, I'll need to see what they plan on doing first before I can proceed.

**Comment by DelofJ** [comment]
I want to clarify that this does not come from the Wavey Capes mod, this problem that the capes do not disappear with the elytra also happens to me with the vanilla capes of the game, for information I use the Fabric version (Elytra Trinket) and the latest versions of each mod which depend on it. Otherwise I also noticed that this problem goes away with the More Banner Features mod

**Comment by TatleCat** [comment]
> 我想澄清一下，这不是来自 Wavey Capes mod，斗篷不会随着鞘翅消失的问题也发生在我身上的游戏的香草斗篷上，作为信息，我使用 Fabric 版本（Elytra Trinket）和依赖于它的每个模组的最新版本。否则，我还注意到这个问题随着更多横幅功能模组的出现而消失

Equipping elytra directly into the elytra slot doesn't give you an achievement, which I think has something to do with that (?
