### ISSUE TITLE
Migrate to use fabric-entity-events-v1 for Elytra flight

### ISSUE THREAD

**Issue by Micalobia** [TheIllusiveC4/CuriousElytra#35]
This mod should migrate to use FabricMC/fabric#1815 to implement its elytra flight. This should help with potential incompatibilities with mods like [Origins](https://github.com/apace100/origins-fabric/issues/465) and [Better End](https://github.com/paulevsGitch/BetterEnd/issues/362)

**Comment by FakeDomi** [comment]
Support for custom elytras will likely still have to be added manually, since the API guarantees that elytra items will be in the chestplate slot.

https://github.com/FabricMC/fabric/blob/1.18/fabric-entity-events-v1/src/main/java/net/fabricmc/fabric/api/entity/event/v1/FabricElytraItem.java#L59

Vanilla elytra items don't break, but it is possible that some custom elytra actually calls the `sendEquipmentBreakStatus` method (or does anything else while expecting the item to be in the chestplate slot).

**Comment by Micalobia** [comment]
That's more a helper utility than a necessity, you can enable it through this event using a condition as well.

https://github.com/FabricMC/fabric/blob/1.18/fabric-entity-events-v1/src/main/java/net/fabricmc/fabric/api/entity/event/v1/EntityElytraEvents.java#L50

**Comment by TheIllusiveC4** [comment]
Done in 3.0.0-1.17.1.
