### ISSUE TITLE
Support For Tinkers Construct Slimelytra

### ISSUE THREAD

**Issue by DeansOnToast** [TheIllusiveC4/CuriousElytra#43]
**Please describe the new feature or change.**
Just looking for support for using Slimelytra in Minecraft 1.16.5
Haven't used any newer versions of Minecraft if its already been implemented.
♥
**Please describe why you want this feature.**

**Comment by TheIllusiveC4** [comment]
Unfortunately, I have no plans to add Slimelytra support. Due to the power of the Slimelytra from Tinkers' Construct, considering its upgradeability, it's a lot more similar to an armored elytra than a regular one. Also, since it was designed as a viable alternative to Tinkers' Construct armor, its power balance is more in line with other chest pieces. I don't think it really belongs in its own slot like regular elytras.
