### ISSUE TITLE
compatibility with Elytra Physics mod

### ISSUE THREAD

**Issue by slovinsqui** [TheIllusiveC4/CuriousElytra#51]
elytra physics does not work when elytra are equipped in cape slot

elytra physics mod link (just in case)= https://www.curseforge.com/minecraft/mc-mods/elytra-physics

**Comment by TheIllusiveC4** [comment]
It looks like Elytra Physics has added this compatibility on their end shortly after this issue was raised.

**Comment by DelofJ** [comment]
There are some rendering issues on Minecraft 1.18.2 with all the mods up-to-date

**Comment by TheIllusiveC4** [comment]
What kind of rendering issues? Elytra Physics's latest update for 1.18.2 says it added compatibility with Elytra Slot, but let me know what kind of issues still exist so that I can see what can be done to correct them.

**Comment by DelofJ** [comment]
Well, the said fix only work for 1.19 and above, on 1.18.2 and before it there is just no physics, it's like the mod is trying to act, but does not entirely
Here is what should happen (did on Minecraft 1.19)
![2023-02-23_01 17 01](https://user-images.githubusercontent.com/50058956/220793643-aa3e516e-33bc-4352-b2fe-50c433bbdd3e.png)
And what actually happens (did on 1.18.2)
![2023-02-23_01 16 01](https://user-images.githubusercontent.com/50058956/220793703-2d327b9a-4d84-4a6a-926e-b6dcbc47a304.png)
And when I saw there was no issues on the Origins mod with Elytra Physics, I assumed modifying the code would fix this, and it did work, that's why I originally forked it for 1.18.2

**Comment by memezboi** [comment]
hi new here, i added this mod and the elytra slot mod in the same modpack i made just to have some fun with friends, but even though everywhere i look it says they are now compatible for 1.19.2, it doesn't work for me. I can load in game but when i go in f5 the cape clips through the elytra and the elytra has no physics. At first i thought it might've been from the wavey caps mod, but i disabled that and it still wasnt working. I have no idea on what to do to fix it and i really want these two mods to work. (FABRIC BTW)
![2023-02-26_12 40 27](https://user-images.githubusercontent.com/51027287/221426905-2a222bfb-7d46-46e1-81cd-c12592dba5dd.png)
![2023-02-26_12 40 13](https://user-images.githubusercontent.com/51027287/221426910-9eeaa837-f2dc-48fb-8da4-de6c1d9452e1.png)
