### ISSUE TITLE
Incompatible with Customizable Elytra?

### ISSUE THREAD

**Issue by NotRuRu** [TheIllusiveC4/CuriousElytra#70]
#### Versions (Be specific, do not write "latest"):
* Elytra Slot:6.2.0+1.19.3
* Trinket:3.5.1
* Quilt: 1.19.3. Quilt version 0.18.3
* Customizable Elytra mod version: 1.6.5-1.19.3
#### Observed Behavior:
If Elytra is dyed, trinket slot no longer functions
#### Expected Behavior:
Equip like a normal Elytra and fly around
#### Steps to Reproduce:
1.Dye elytra ( Customizable Elytra mod)
2. put it in Trinket slot, like you would with normal elytra ( Elytra Slot Mod)
3. it shows in the inventory but you wont be able to fly
...
Is mod not compatible with customizable elytra mod?
here is mod list just incase ( I removed all other mods to see if it would work and it still didnt work)
![image](https://user-images.githubusercontent.com/92341439/225161175-92f6f701-bfc1-4f5e-b484-78fcd285116a.png)

**Comment by Burning-Water** [comment]
Heres the mod they are referring to. its likely because it changes the "Minecraft" tag at the bottom of the description to customizable elytra as well as other descriptions. would it be possible to copy all the nbt data from whatever elytra is in the elytra slot and set that as the equipped elytra? similarly to how you have set all the enchantments to transfer over? this would probably fix the issues surrounding other mod compatibilities as well.
https://www.curseforge.com/minecraft/mc-mods/elytra-slot-fabric

**Comment by TheIllusiveC4** [comment]
This was resolved by Customizable Elytra on their end.
