### ISSUE TITLE
[Bug]: Crash Error Exit Code 1 

### ISSUE THREAD

**Issue by TonyC1089** [TheIllusiveC4/CuriousElytra#86]
### Minecraft Version

1.20.1

### What happened?

Whenever I launch Minecraft with the mod installed, Minecraft would crash and give back an error code: Exit Code:1. After looking and seeking help from the Minecraft server, there seems to be an error when this mod is installed with AppliedEnergisitcs 2. The mod is unable to access MysteriousCubeBlock entity, causing the crash

### How do you trigger this bug?

1. AppliedEnergistics 2 Mod
2.
3.
...

### Loader

Forge

### Loader Version

Forge 47.1.0

### API Version

N/A

### Mod Version

Elytra Slot 1.20.1

### Relevant Log Outputs

https://paste.gg/p/anonymous/2f3a9002fed047788fc176976d81f315

**Comment by TheIllusiveC4** [comment]
This mod doesn't access anything from Applied Energistics 2, so it's unlikely to be the cause. However, I also see that the log mentions that you are missing Caelus, a required dependency for this mod, so that would be another reason that the game fails to launch. Once that's resolved, if the `MysteriousCubeBlock` situation still occurs, it's unlikely to be related to Elytra Slot.
